config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :keywords
  resources :career_fields
  resources :about_us

  resources :stakeholders do
    resources :users
    resource :profile, only: [:show, :edit, :update]
  end
  devise_for :users

  root 'posts#index'

  match 'posts', to: 'posts#index', via: [:get, :post]

end

app/models/career_field.rb
class CareerField < ActiveRecord::Base
  has_and_belongs_to_many :keywords
end

app/controllers/career_fields_controller.rb
class CareerFieldsController < ApplicationController
  before_action :set_career_field, only: [:show, :edit, :update, :destroy]
  prepend_before_action :admin_only
  prepend_before_action :authenticate_user!


  # GET /career_fields
  # GET /career_fields.json
  def index
    @career_fields = CareerField.paginate(:page => params[:page])
  end

  # GET /career_fields/1
  # GET /career_fields/1.json
  def show
  end

  # GET /career_fields/new
  def new
    @career_field = CareerField.new
  end

  # GET /career_fields/1/edit
  def edit
  end

  # POST /career_fields
  # POST /career_fields.json
  def create
    @career_field = CareerField.new(career_field_params)

    respond_to do |format|
      if @career_field.save
        format.html { redirect_to @career_field, notice: 'Career field was successfully created.' }
        format.json { render :show, status: :created, location: @career_field }
      else
        format.html { render :new }
        format.json { render json: @career_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /career_fields/1
  # PATCH/PUT /career_fields/1.json
  def update
    respond_to do |format|
      if @career_field.update(career_field_params)
        format.html { redirect_to @career_field, notice: 'Career field was successfully updated.' }
        format.json { render :show, status: :ok, location: @career_field }
      else
        format.html { render :edit }
        format.json { render json: @career_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /career_fields/1
  # DELETE /career_fields/1.json
  def destroy
    @career_field.destroy
    respond_to do |format|
      format.html { redirect_to career_fields_url, notice: 'Career field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_career_field
      @career_field = CareerField.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def career_field_params
      params.require(:career_field).permit(:label, :active, keyword_ids: [])
    end
end

app/helpers/career_fields_helper.rb
module CareerFieldsHelper
end

app/views/career_fields/_form.html.erb
<%= simple_form_for(@career_field) do |f| %>
    <%= f.input :label %>
    <%= f.association :keywords, label_method: :label, as: :check_boxes %>
    <%= f.input :active %>

    <%= f.button :submit %>
<% end %>

app/views/career_fields/edit.html.erb
<h1>Editing Career Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @career_field %> |
<%= link_to 'Back', career_fields_path %>

app/views/career_fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Career Fields</h1>

<div class="row">
  <% @career_fields.each do |career_field| %>
      <div class="col-sm-4">
        <div class="card card-block">
          <h4 class="card-title"><%= career_field.label %></h4>
          <p class="card-text">
            <% career_field.keywords.each do |keyword| %>
                <li><%= keyword.label %></li>
            <% end %>
          </p>
          <%= link_to 'Show', career_field, class: 'card-link' %>
          <%= link_to 'Edit', edit_career_field_path(career_field), class: 'card-link' %>
          <%= link_to 'Destroy', career_field, method: :delete, data: {confirm: 'Are you sure?'}, class: 'card-link' %>
        </div>
      </div>
  <% end %>
</div>

<%= will_paginate @career_fields %>


<br>

<div class="row">
  <%= link_to 'New Career field', new_career_field_path, class: 'btn btn-info' %>
</div>

app/views/career_fields/new.html.erb
<h1>New Career Field</h1>

<%= render 'form' %>

<%= link_to 'Back', career_fields_path %>

app/views/career_fields/show.html.erb
<p>
  <strong>Label:</strong>
  <%= @career_field.label %>
</p>

<p>
  <strong>Active:</strong>
  <%= @career_field.active %>
</p>

<%= link_to 'Edit', edit_career_field_path(@career_field) %> |
<%= link_to 'Back', career_fields_path %>