config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :keywords
  resources :career_fields
  resources :about_us

  resources :stakeholders do
    resources :users
    resource :profile, only: [:show, :edit, :update]
  end
  devise_for :users

  root 'posts#index'

  match 'posts', to: 'posts#index', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :stakeholder
  has_many :user_roles

  attr_accessor :is_admin

  def is_admin?
    !self.user_roles.find_by_role(UserRole.roles[:admin]).nil?
  end

  def is_stakeholder_admin?
    !self.user_roles.find_by_role(UserRole.roles[:stakeholder_admin]).nil?
  end

  self.per_page = 10
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_stakeholder

  prepend_before_action :stakeholder_admin_only
  prepend_before_action :authenticate_user!
  prepend_before_action :has_stakeholder_access, only: [:create]


  # GET /users
  # GET /users.json
  def index
    @users = @stakeholder.users.paginate(:page => params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = @stakeholder.users.new(params[:user])
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    p = user_params
    p[:password] = SecureRandom.base64(8)

    @user = User.new(p)

    respond_to do |format|
      if @user.save
        if p[:is_admin]
          @user.user_roles.create(role: UserRole.roles[:stakeholder_admin])
        end

        @user.send_reset_password_instructions
        format.html { redirect_to [@stakeholder, @user], notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: [@stakeholder, @user] }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [@stakeholder, @user], notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: [@stakeholder, @user]  }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def set_stakeholder
    @stakeholder = Stakeholder.find(params[:stakeholder_id])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def has_stakeholder_access
    sameStakeholder = (current_user.stakeholder_id === user_params[:stakeholder_id].to_i)

    if !sameStakeholder && !current_user.is_admin?
      redirect_to new_stakeholder_user_url, :alert => 'Access denied. -> you do not have access to this stakeholder'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :stakeholder_id, :is_admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for([@stakeholder, @user]) do |f| %>
    <%= f.input :stakeholder_id, as: :hidden %>
    <%= f.input :email %>

    <%= f.input :is_admin do %>
      <%= check_box_tag 'user[is_admin]' %>
    <% end %>

    <%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', [@stakeholder, @user] %> |
<%= link_to 'Back', stakeholder_users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Email</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %> </td>
        <td><%= link_to 'Show', stakeholder_user_path(@stakeholder, user) %></td>
        <td><%= link_to 'Edit', edit_stakeholder_user_path(@stakeholder, user) %></td>
        <td><%= link_to 'Destroy', stakeholder_users_url, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @users%>


<br>

<%= link_to 'New User', new_stakeholder_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', stakeholder_users_path %>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong>

  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_stakeholder_user_path(@stakeholder, @user) %> |
<%= link_to 'Back', stakeholder_users_path %>