config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :keywords
  resources :career_fields
  resources :about_us

  resources :stakeholders do
    resources :users
    resource :profile, only: [:show, :edit, :update]
  end
  devise_for :users

  root 'posts#index'

  match 'posts', to: 'posts#index', via: [:get, :post]

end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base
  has_one :profile
  has_many :users
  has_and_belongs_to_many :keywords
  has_many :posts
  after_create :postCreate

  self.per_page = 10

  def postCreate
    create_profile(email: 'placeholder@placeholder.com' )
  end
end

app/controllers/stakeholders_controller.rb
class StakeholdersController < ApplicationController
  before_action :set_stakeholder, only: [:show, :edit, :update, :destroy]
  prepend_before_action :admin_only, only: [:edit, :update, :new, :create, :destroy]
  prepend_before_action :authenticate_user!, only: [:edit, :update, :new, :create, :destroy]


  # GET /stakeholders
  # GET /stakeholders.json
  def index
    @stakeholders = Stakeholder.paginate(:page => params[:page])
  end

  # GET /stakeholders/1
  # GET /stakeholders/1.json
  def show
  end

  # GET /stakeholders/new
  def new
    @stakeholder = Stakeholder.new
  end

  # GET /stakeholders/1/edit
  def edit
  end

  # POST /stakeholders
  # POST /stakeholders.json
  def create
    @stakeholder = Stakeholder.new(stakeholder_params)

    respond_to do |format|
      if @stakeholder.save
        format.html { redirect_to @stakeholder, notice: 'Stakeholder was successfully created.' }
        format.json { render :show, status: :created, location: @stakeholder }
      else
        format.html { render :new }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stakeholders/1
  # PATCH/PUT /stakeholders/1.json
  def update
    respond_to do |format|
      if @stakeholder.update(stakeholder_params)
        format.html { redirect_to @stakeholder, notice: 'Stakeholder was successfully updated.' }
        format.json { render :show, status: :ok, location: @stakeholder }
      else
        format.html { render :edit }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stakeholders/1
  # DELETE /stakeholders/1.json
  def destroy
    @stakeholder.destroy
    respond_to do |format|
      format.html { redirect_to stakeholders_url, notice: 'Stakeholder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stakeholder
      @stakeholder = Stakeholder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stakeholder_params
      params.require(:stakeholder).permit(:name)
    end
end

app/helpers/stakeholders_helper.rb
module StakeholdersHelper
end

app/views/stakeholders/_form.html.erb
<%= simple_form_for(@stakeholder) do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
<% end %>

app/views/stakeholders/edit.html.erb
<h1>Editing Stakeholder</h1>

<%= render 'form' %>

<%= link_to 'Show', @stakeholder %> |
<%= link_to 'Back', stakeholders_path %>

app/views/stakeholders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stakeholders</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th >Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @stakeholders.each do |stakeholder| %>
      <tr>
        <td><%= stakeholder.name %></td>
        <td><%= link_to 'Show', stakeholder %></td>
        <td><%= link_to 'Edit', edit_stakeholder_path(stakeholder) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @stakeholders %>


<br>

<%= link_to 'New Stakeholder', new_stakeholder_path %>

app/views/stakeholders/new.html.erb
<h1>New Stakeholder</h1>

<%= render 'form' %>

<%= link_to 'Back', stakeholders_path %>

app/views/stakeholders/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @stakeholder.name %>
</p>

<%= link_to 'Edit', edit_stakeholder_path(@stakeholder) %> |
<%= link_to 'Back', stakeholders_path %>

</br></br></br>

<p>
  <%= link_to 'View Profile', [@stakeholder, @stakeholder.profile] %> |
  <%= link_to 'View Posts', :controller => :posts, :action => 'index', :stakeholder_id => @stakeholder.id %> |
  <%= link_to 'Create New Post', :controller => :posts, :action => 'new', :stakeholder_id => @stakeholder.id %> |
  <%= link_to 'Create New User', :controller => :users, :action => 'new', :stakeholder_id => @stakeholder.id %> |
  <%= link_to 'View Users', :controller => :users, :action => 'index', :stakeholder_id => @stakeholder.id %>
</p>