config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :keywords
  resources :career_fields
  resources :about_us

  resources :stakeholders do
    resources :users
    resource :profile, only: [:show, :edit, :update]
  end
  devise_for :users

  root 'posts#index'

  match 'posts', to: 'posts#index', via: [:get, :post]

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  has_and_belongs_to_many :stakeholders
  has_and_belongs_to_many :career_fields
  has_and_belongs_to_many :posts
  validates :label, presence: true


  def self.search(search)
    if search
      where("label LIKE ?", "%#{search}%")
    else
      find(:all)
    end
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]
  prepend_before_action :admin_only, :except => [:index]
  prepend_before_action :authenticate_user!, :except => [:index]


  # GET /keywords
  # GET /keywords.json
  def index

    if params[:label]
      @keywords = Keyword.search(params[:label])
    else
      @keywords = Keyword.paginate(:page => params[:page])
    end

  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:label)
    end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= simple_form_for(@keyword) do |f| %>
    <%= f.input :label %>

    <%= f.button :submit %>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing Keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Keywords</h1>

<div class="row">
  <% @keywords.each do |keyword| %>
      <div class="col-sm-4">
        <div class="card card-block">
          <h4 class="card-title"><%= keyword.label %></h4>
          <p class="card-text">
          </p>
          <%= link_to 'Show', keyword, class: 'card-link' %>
          <%= link_to 'Edit', edit_keyword_path(keyword), class: 'card-link' %>
          <%= link_to 'Destroy', keyword, method: :delete, data: {confirm: 'Are you sure?'}, class: 'card-link' %>
        </div>
      </div>
  <% end %>
</div>

<%= will_paginate @keywords %>


<br>

<div class="row">
  <%= link_to 'New Keyword', new_keyword_path, class: 'btn btn-info' %>
</div>

app/views/keywords/new.html.erb
<h1>New Keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p>
  <strong>Label:</strong>
  <%= @keyword.label %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>